<?xml version="1.0"?>
<package format="3">
  <name>rb23_audio</name>
  <version>0.0.0</version>
  <description>Nó de áudio do GuardROS para o RB23</description>

  <maintainer email="denis.mosconi@ifsp.edu.br">denis</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>guardros_msgs</depend>

  <exec_depend>python3-numpy</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>